skip_clone: true
when:
  - branch: master
    event: push

steps:
  - name: clone to build-artifacts
    image: sh
    environment:
      BUILD_DIR: /mnt/build-artifacts/blog
    commands:
      - rm -rf "$BUILD_DIR"/*
      - rm -rf "$BUILD_DIR"/.[!.]* 2>/dev/null || true
      - git clone --recurse-submodules "$CI_REPO_CLONE_URL" .
      - cp -r . "$BUILD_DIR/"

  - name: redeploy
    image: sh
    commands:
      - ssh blog
